name: Bazjuk CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show repository structure
        run: ls -la

      - name: CI test message
        run: echo "CI/CD pipeline працює успішно"
